<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Mraipd */

$this->title = $model->mra_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Mraipds'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="mraipd-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->mra_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->mra_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'mra_id',
            'unit_id',
            'HN',
            'AN',
            'dr_license',
            'date_admit',
            'date_discharge',
            'date_audit',
            'NA1',
            'Missing1',
            'No1',
            'dxop1',
            'dxop2',
            'dxop3',
            'dxop4',
            'dxop5',
            'dxop6',
            'dxop7',
            'dxop8',
            'dxop9',
            'dxop_huk',
            'NA2',
            'Missing2',
            'No2',
            'other1',
            'other2',
            'other3',
            'other4',
            'other5',
            'other6',
            'other7',
            'other8',
            'other9',
            'other_huk',
            'NA3',
            'Missing3',
            'No3',
            'infc1',
            'infc2',
            'infc3',
            'infc4',
            'infc5',
            'infc6',
            'infc7',
            'infc8',
            'infc9',
            'infc_huk',
            'NA4',
            'Missing4',
            'No4',
            'hist1',
            'hist2',
            'hist3',
            'hist4',
            'hist5',
            'hist6',
            'hist7',
            'hist8',
            'hist9',
            'hist_huk',
            'NA5',
            'Missing5',
            'No5',
            'pe1',
            'pe2',
            'pe3',
            'pe4',
            'pe5',
            'pe6',
            'pe7',
            'pe8',
            'pe9',
            'pe_huk',
            'NA6',
            'Missing6',
            'No6',
            'pn1',
            'pn2',
            'pn3',
            'pn4',
            'pn5',
            'pn6',
            'pn7',
            'pn8',
            'pn9',
            'pn_huk',
            'NA7',
            'Missing7',
            'No7',
            'cr1',
            'cr2',
            'cr3',
            'cr4',
            'cr5',
            'cr6',
            'cr7',
            'cr8',
            'cr9',
            'cr_huk',
            'NA8',
            'Missing8',
            'No8',
            'ar1',
            'ar2',
            'ar3',
            'ar4',
            'ar5',
            'ar6',
            'ar7',
            'ar8',
            'ar9',
            'ar_huk',
            'NA9',
            'Missing9',
            'No9',
            'on1',
            'on2',
            'on3',
            'on4',
            'on5',
            'on6',
            'on7',
            'on8',
            'on9',
            'on_huk',
            'NA10',
            'Missing10',
            'No10',
            'lr1',
            'lr2',
            'lr3',
            'lr4',
            'lr5',
            'lr6',
            'lr7',
            'lr8',
            'lr9',
            'lr_huk',
            'NA11',
            'Missing11',
            'No11',
            'rr1',
            'rr2',
            'rr3',
            'rr4',
            'rr5',
            'rr6',
            'rr7',
            'rr8',
            'rr9',
            'rr_huk',
            'NA12',
            'Missing12',
            'No12',
            'nn1',
            'nn2',
            'nn3',
            'nn4',
            'nn5',
            'nn6',
            'nn7',
            'nn8',
            'nn9',
            'nn_huk',
            'hospcode',
        ],
    ]) ?>

</div>
