<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Mraopd */

$this->title = $model->mra_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Mraopds'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="mraopd-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->mra_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->mra_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'mra_id',
            'unit_id',
            'HN',
            'AN',
            'dr_license',
            'date_admit',
            'date_discharge',
            'date_audit',
            'NA01',
            'MI01',
            'NO01',
            'SC011',
            'SC012',
            'SC013',
            'SC014',
            'SC015',
            'SC016',
            'SC017',
            'SC018',
            'SC019',
            'PEIM01',
            'DEC01',
            'NA02',
            'MI02',
            'NO02',
            'SC021',
            'SC022',
            'SC023',
            'SC024',
            'SC025',
            'SC026',
            'SC027',
            'SC028',
            'SC029',
            'PEIM02',
            'DEC02',
            'NA03',
            'MI03',
            'NO03',
            'SC031',
            'SC032',
            'SC033',
            'SC034',
            'SC035',
            'SC036',
            'SC037',
            'SC038',
            'SC039',
            'PEIM03',
            'DEC03',
            'NA04',
            'MI04',
            'NO04',
            'SC041',
            'SC042',
            'SC043',
            'SC044',
            'SC045',
            'SC046',
            'SC047',
            'SC048',
            'SC049',
            'PEIM04',
            'DEC04',
            'NA05',
            'MI05',
            'NO05',
            'SC051',
            'SC052',
            'SC053',
            'SC054',
            'SC055',
            'SC056',
            'SC057',
            'SC058',
            'SC059',
            'PEIM05',
            'DEC05',
            'Followdate1',
            'Followdate2',
            'NA06',
            'MI06',
            'NO06',
            'SC061',
            'SC062',
            'SC063',
            'SC064',
            'SC065',
            'SC066',
            'SC067',
            'SC068',
            'SC069',
            'PEIM06',
            'DEC06',
            'Followdate3',
            'NA07',
            'MI07',
            'NO07',
            'SC071',
            'SC072',
            'SC073',
            'SC074',
            'SC075',
            'SC076',
            'SC077',
            'SC078',
            'SC079',
            'PEIM07',
            'DEC07',
            'NA08',
            'MI08',
            'NO08',
            'SC081',
            'SC082',
            'SC083',
            'SC084',
            'SC085',
            'SC086',
            'SC087',
            'SC088',
            'SC089',
            'PEIM08',
            'DEC08',
            'NA09',
            'MI09',
            'NO09',
            'SC091',
            'SC092',
            'SC093',
            'SC094',
            'SC095',
            'SC096',
            'SC097',
            'SC098',
            'SC099',
            'PEIM09',
            'DEC09',
            'NA10',
            'MI10',
            'NO10',
            'SC101',
            'SC102',
            'SC103',
            'SC104',
            'SC105',
            'SC106',
            'SC107',
            'SC108',
            'SC109',
            'PEIM10',
            'DEC10',
            'hospcode',
        ],
    ]) ?>

</div>
